# Generated by Django 5.2.7 on 2026-05-27 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contrasenia', models.CharField(max_length=255)),
                ('nombre_usuario', models.CharField(max_length=255, unique=True)),
                ('tarifa', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Asesorado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contrasenia', models.CharField(max_length=255)),
                ('nombre_usuario', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('dificultad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Asesoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('confirmada', models.BooleanField(default=False)),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.asesor')),
                ('asesorado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.asesorado')),
            ],
        ),
        migrations.CreateModel(
            name='TemasDelAsesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.asesor')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.tema')),
            ],
        ),
    ]
