# Generated by Django 5.2.7 on 2026-05-29 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id_asesor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contrasenia', models.CharField(max_length=255)),
                ('nombre_usuario', models.CharField(max_length=255, unique=True)),
                ('tarifa', models.FloatField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('modalidad', models.CharField(choices=[('Individual', 'Individual'), ('Grupal', 'Grupal')], default='Individual', max_length=20)),
                ('promedio_calificacion', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('disponibilidad', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ASESOR',
            },
        ),
        migrations.CreateModel(
            name='Asesorado',
            fields=[
                ('id_asesorado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contrasenia', models.CharField(max_length=255)),
                ('nombre_usuario', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'ASESORADO',
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id_tema', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('dificultad', models.IntegerField()),
            ],
            options={
                'db_table': 'TEMA',
            },
        ),
        migrations.CreateModel(
            name='Asesoria',
            fields=[
                ('id_asesoria', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Individual', 'Individual'), ('Grupal', 'Grupal')], max_length=20)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada'), ('Finalizada', 'Finalizada')], default='Pendiente', max_length=20)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('asesor', models.ForeignKey(db_column='id_asesor', on_delete=django.db.models.deletion.CASCADE, to='usuarios.asesor')),
                ('asesorado', models.ForeignKey(db_column='id_asesorado', on_delete=django.db.models.deletion.CASCADE, to='usuarios.asesorado')),
            ],
            options={
                'db_table': 'ASESORIA',
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('puntuacion', models.IntegerField()),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('asesoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.asesoria')),
            ],
            options={
                'db_table': 'CALIFICACION',
            },
        ),
        migrations.CreateModel(
            name='GrupoAsesoria',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('asesoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.asesoria')),
            ],
            options={
                'db_table': 'GRUPO_ASESORIA',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('disponible', models.BooleanField(default=True)),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.asesor')),
            ],
            options={
                'db_table': 'HORARIO',
            },
        ),
        migrations.AddField(
            model_name='asesoria',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.horario'),
        ),
        migrations.CreateModel(
            name='IntegranteGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asesorado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.asesorado')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.grupoasesoria')),
            ],
            options={
                'db_table': 'INTEGRANTE_GRUPO',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.asesor')),
            ],
            options={
                'db_table': 'NOTIFICACION',
            },
        ),
        migrations.CreateModel(
            name='TemasDelAsesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.asesor')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.tema')),
            ],
            options={
                'db_table': 'TEMASDELASESOR',
            },
        ),
    ]
